[tool.poetry]
name = "mk3-train"
version = "0.1.0"
description = ""
authors = ["Pavel Kalashnikov"]

[tool.poetry.dependencies]
python = ">= 3.6.0"
stable_baselines = "2.10.0"
gym = "0.15.7"
gym-retro = "0.8.0"
tensorflow = "1.15.5"
cloudpickle = "1.2.0"
